# GitLab CI/CD para Pages
stages:
  - deploy

pages:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache rsync
  script:
    # Criar diretório public
    - mkdir -p public
    
    # Copiar todos os arquivos para public, exceto arquivos desnecessários
    - rsync -av --exclude='.git*' --exclude='public' --exclude='node_modules' --exclude='*.md' ./ public/
    
    # Verificar se o index.html existe
    - ls -la public/
    - test -f public/index.html || (echo "Error: index.html not found!" && exit 1)
    
  artifacts:
    paths:
      - public
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  
# Job para testar o site (opcional)
test-html:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Testando estrutura HTML..."
    - test -f index.html || (echo "index.html não encontrado!" && exit 1)
    - echo "✅ Estrutura HTML válida"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"