pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html public/
    - cp yanLuca.png public/ 2>/dev/null || true
    - cp -r certificados public/ 2>/dev/null || true
    - cp -r projetos public/ 2>/dev/null || true
    - cp *.html public/ 2>/dev/null || true
    - ls -la public/
    - du -sh public/
  artifacts:
    paths:
      - public
  only:
    - main