name: 🔄 Sync to GitLab

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  sync:
    name: 📡 Mirror to GitLab
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: 🔧 Setup SSH
      run: |
        # Criar diretório SSH
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        # Adicionar chave SSH
        echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
        # Adicionar GitLab aos known hosts
        ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
        
        # Configurar SSH para usar a chave correta
        cat > ~/.ssh/config << EOF
        Host gitlab.com
            HostName gitlab.com
            User git
            IdentityFile ~/.ssh/id_ed25519
            IdentitiesOnly yes
        EOF
        chmod 600 ~/.ssh/config
        
        # Testar conexão
        ssh -T git@gitlab.com || true
        
    - name: 🪞 Mirror to GitLab
      run: |
        # Configurar Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Adicionar remote do GitLab se não existir
        git remote add gitlab git@gitlab.com:lhuck4z/yan-luca.git || true
        
        # Fazer push para GitLab
        git push gitlab --all --force
        git push gitlab --tags --force
        
    - name: ✅ Sync Completed
      run: echo "🎉 Successfully synced to GitLab!"