name: Sync to GitLab

on:
  push:
    branches: [ main, master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Mirror to GitLab
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: git@gitlab.com:lhuck4z/yan-luca.git
        ssh_private_key: ${{ secrets.GITLAB_SSH_KEY }}